# Generated by Django 2.2.2 on 2019-07-03 15:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_reference', models.CharField(max_length=100)),
                ('list_feedbacks', django_mysql.models.ListCharField(models.CharField(max_length=200), max_length=660000, size=600)),
            ],
            options={
                'verbose_name_plural': 'feedbacks',
            },
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_reference', models.CharField(max_length=100)),
                ('list_photos_profile', django_mysql.models.ListCharField(models.CharField(max_length=200), max_length=660000, size=600)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_reference', models.CharField(max_length=100)),
                ('list_posts', django_mysql.models.ListCharField(models.CharField(max_length=200), max_length=660000, size=600)),
            ],
            options={
                'verbose_name_plural': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Seguidores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_reference', models.CharField(max_length=100)),
                ('status_follor', models.BooleanField(default=False)),
                ('list_followers', django_mysql.models.ListCharField(models.CharField(max_length=200), max_length=660000, size=600)),
            ],
            options={
                'verbose_name_plural': 'seguidores',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_reference', models.CharField(max_length=100)),
                ('list_tag', django_mysql.models.ListCharField(models.CharField(max_length=200), max_length=660000, size=600)),
            ],
            options={
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Userx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=400)),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('identifier', models.CharField(max_length=200)),
                ('actived', models.BooleanField(default=True)),
                ('status', models.CharField(default=None, max_length=200, null=True)),
                ('key', models.CharField(default=None, max_length=200, null=True, verbose_name='Key')),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_api', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Perfis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('amount', models.IntegerField(default=True, max_length=200)),
                ('identifier', models.CharField(max_length=200, null=True)),
                ('feedbacks', models.ManyToManyField(default=None, null=True, to='umbrella_application.Feedbacks')),
                ('photos', models.ManyToManyField(default=None, null=True, to='umbrella_application.Photos')),
                ('posts', models.ManyToManyField(default=None, null=True, to='umbrella_application.Posts')),
                ('seguidores', models.ManyToManyField(default=None, null=True, to='umbrella_application.Seguidores')),
                ('tags', models.ManyToManyField(default=None, null=True, to='umbrella_application.Tags')),
            ],
            options={
                'verbose_name_plural': 'perfis',
            },
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default=None, max_length=100, null=True)),
                ('id_perfil_select', models.CharField(max_length=2000, null=True)),
                ('id_gestor_select', models.CharField(max_length=2000, null=True)),
                ('Perfis', models.ManyToManyField(blank=True, null=True, to='umbrella_application.Perfis')),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='umbrella_application.Userx')),
            ],
            options={
                'verbose_name_plural': 'gestores',
            },
        ),
    ]
