# Generated by Django 2.0.13 on 2019-06-21 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfis',
            name='identifier',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
