# Generated by Django 2.0.13 on 2019-06-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfis',
            name='amount',
            field=models.IntegerField(default=True, max_length=200),
        ),
    ]
