# Generated by Django 2.0.13 on 2019-05-17 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbacks',
            options={'verbose_name_plural': 'feedbacks'},
        ),
    ]
