# Generated by Django 2.0.13 on 2019-06-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella_application', '0002_perfis_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestor',
            name='id_perfil_select',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
