# Generated by Django 2.0.13 on 2019-06-21 05:09

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella_application', '0002_perfis_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguidores',
            name='list_followers',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=6600, size=60),
        ),
    ]
