# Generated by Django 2.0.13 on 2019-06-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella_application', '0003_gestor_id_perfil_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestor',
            name='id_gestor_select',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
