# Generated by Django 2.0.13 on 2019-06-21 15:35

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella_application', '0003_auto_20190621_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='list_feedbacks',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=660000, size=600),
        ),
        migrations.AlterField(
            model_name='posts',
            name='list_posts',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=660000, size=600),
        ),
        migrations.AlterField(
            model_name='seguidores',
            name='list_followers',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=660000, size=600),
        ),
        migrations.AlterField(
            model_name='tags',
            name='list_tag',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=660000, size=600),
        ),
    ]
