# Generated by Django 2.0.13 on 2019-06-21 16:29

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella_application', '0004_auto_20190621_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_reference', models.CharField(max_length=100)),
                ('list_photos_profile', django_mysql.models.ListCharField(models.CharField(max_length=200), max_length=660000, size=600)),
            ],
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='list_feedbacks',
            field=django_mysql.models.ListCharField(models.CharField(max_length=200), max_length=660000, size=600),
        ),
        migrations.AlterField(
            model_name='posts',
            name='list_posts',
            field=django_mysql.models.ListCharField(models.CharField(max_length=200), max_length=660000, size=600),
        ),
        migrations.AlterField(
            model_name='seguidores',
            name='list_followers',
            field=django_mysql.models.ListCharField(models.CharField(max_length=200), max_length=660000, size=600),
        ),
        migrations.AlterField(
            model_name='tags',
            name='list_tag',
            field=django_mysql.models.ListCharField(models.CharField(max_length=200), max_length=660000, size=600),
        ),
        migrations.AddField(
            model_name='perfis',
            name='photos',
            field=models.ManyToManyField(default=None, null=True, to='umbrella_application.Photos'),
        ),
    ]
