# Generated by Django 2.0.13 on 2019-04-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=400)),
                ('email', models.CharField(max_length=400)),
                ('username', models.CharField(max_length=400)),
                ('password', models.CharField(max_length=200)),
                ('identifier', models.CharField(max_length=200)),
                ('actived', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'gestores',
            },
        ),
    ]
