# Generated by Django 2.0.13 on 2019-05-17 16:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_reference', models.CharField(max_length=100)),
                ('list_feedbacks', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
            ],
            options={
                'verbose_name_plural': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('identifier', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'gestores',
            },
        ),
        migrations.CreateModel(
            name='Perfis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('feedbacks', models.ManyToManyField(default=None, null=True, to='umbrella.Feedbacks')),
            ],
            options={
                'verbose_name_plural': 'perfis',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_reference', models.CharField(max_length=100)),
                ('list_posts', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
            ],
            options={
                'verbose_name_plural': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Seguidores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_reference', models.CharField(max_length=100)),
                ('status_follor', models.BooleanField(default=False)),
                ('list_followers', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
            ],
            options={
                'verbose_name_plural': 'seguidores',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_reference', models.CharField(max_length=100)),
                ('list_tag', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
            ],
            options={
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Userx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=400)),
                ('created_at', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('identifier', models.CharField(max_length=200)),
                ('actived', models.BooleanField(default=True)),
                ('status', models.CharField(default=None, max_length=200, null=True)),
                ('key', models.CharField(default=None, max_length=200, null=True, verbose_name='Key')),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_api', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'users',
            },
        ),
        migrations.AddField(
            model_name='perfis',
            name='posts',
            field=models.ManyToManyField(default=None, null=True, to='umbrella.Posts'),
        ),
        migrations.AddField(
            model_name='perfis',
            name='seguidores',
            field=models.ManyToManyField(default=None, null=True, to='umbrella.Seguidores'),
        ),
        migrations.AddField(
            model_name='perfis',
            name='tags',
            field=models.ManyToManyField(default=None, null=True, to='umbrella.Tags'),
        ),
        migrations.AddField(
            model_name='gestor',
            name='Perfis',
            field=models.ManyToManyField(blank=True, null=True, to='umbrella.Perfis'),
        ),
        migrations.AddField(
            model_name='gestor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='umbrella.Userx'),
        ),
    ]
