# Generated by Django 2.0.13 on 2019-05-01 02:54

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_reference', models.CharField(max_length=100)),
                ('list_feedbacks', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
            ],
            options={
                'verbose_name_plural': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Perfis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('feedbacks', models.ManyToManyField(to='umbrella.Feedbacks')),
            ],
            options={
                'verbose_name_plural': 'perfis',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_reference', models.CharField(max_length=100)),
                ('list_posts', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
            ],
            options={
                'verbose_name_plural': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Seguidores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_reference', models.CharField(max_length=100)),
                ('list_followers', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
            ],
            options={
                'verbose_name_plural': 'seguidores',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_reference', models.CharField(max_length=100)),
                ('list_tag', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
            ],
            options={
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('nome', models.CharField(max_length=400)),
                ('email', models.CharField(max_length=400)),
                ('username', models.CharField(max_length=400)),
                ('password', models.CharField(max_length=200)),
                ('identifier', models.CharField(max_length=200)),
                ('actived', models.BooleanField(default=True)),
                ('status', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Key')),
            ],
            options={
                'verbose_name_plural': 'users',
            },
        ),
        migrations.RemoveField(
            model_name='gestor',
            name='actived',
        ),
        migrations.RemoveField(
            model_name='gestor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='gestor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gestor',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='gestor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='gestor',
            name='username',
        ),
        migrations.AlterField(
            model_name='gestor',
            name='identifier',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='perfis',
            name='posts',
            field=models.ManyToManyField(to='umbrella.Posts'),
        ),
        migrations.AddField(
            model_name='perfis',
            name='seguidores',
            field=models.ManyToManyField(to='umbrella.Seguidores'),
        ),
        migrations.AddField(
            model_name='perfis',
            name='tags',
            field=models.ManyToManyField(to='umbrella.Tags'),
        ),
        migrations.AddField(
            model_name='gestor',
            name='Perfis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='umbrella.Perfis'),
        ),
        migrations.AddField(
            model_name='gestor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='umbrella.User'),
        ),
    ]
