# Generated by Django 2.0.13 on 2019-05-01 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella', '0002_auto_20190501_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestor',
            name='Perfis',
        ),
        migrations.AddField(
            model_name='gestor',
            name='Perfis',
            field=models.ManyToManyField(blank=True, null=True, to='umbrella.Perfis'),
        ),
    ]
